#ifndef GEOLOGICOSM_GLOBAL_H
#define GEOLOGICOSM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOLOGICOSM_LIBRARY)
#  define GEOLOGICOSMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GEOLOGICOSMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOLOGICOSM_GLOBAL_H
