/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f4xx.h"
#include <stdint.h>

int main(void)
{
    /* Loop forever */
	GPIO_TypeDef* gpioa = GPIOA;

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN;

	// PA5 out
	gpioa->MODER &= (~GPIO_MODER_MODER5_Msk);
	gpioa->MODER |= GPIO_MODER_MODER5_0;

	// PC13 in
	GPIO_TypeDef* gpioc = GPIOC;
	gpioc->MODER &= (~GPIO_MODER_MODER13_Msk);
	// no need to set to input because value = 00

	uint32_t max1 = 100000;
	uint32_t max2 = max1 * 3;
	uint32_t max = max1;
	(void) max;
	(void) max1;
	(void) max2;

	uint32_t debounce = 250000;
	uint32_t decounceCounter = debounce;

	uint32_t counter = 0;
	for(;;) {
		//button
		if(decounceCounter < debounce) {
			++decounceCounter;
		} else {
			// user button is pull up so check if 0
			if((gpioc->IDR & GPIO_IDR_ID13) == 0) {
				max = (max == max1) ? max2 : max1;
				decounceCounter = 0;
			}
		}

		// led
		if(counter < max) {
			++counter;
		} else {
			uint8_t newLedState = ! (gpioa->ODR & GPIO_ODR_OD5_Msk);
			gpioa->ODR &= (~GPIO_ODR_OD5_Msk);
			gpioa->ODR |= (newLedState << GPIO_ODR_OD5_Pos);
			counter = 0;
		}
	}
}
